# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-12 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stats', '0035_score_ai_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortieAugmentation',
            fields=[
                ('sortie', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='SortieAugmentation_MOD_SPLIT_RANKINGS', serialize=False, to='stats.Sortie')),
                ('cls', models.CharField(blank=True, choices=[('heavy', 'heavy'), ('medium', 'medium'), ('light', 'light'), ('placeholder', 'placeholder')], max_length=16)),
            ],
            options={
                'db_table': 'Sortie_MOD_SPLIT_RANKINGS',
            },
        ),
    ]
