# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-08 13:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0036_pt_br'),
        ('mod_rating_by_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerAugmentation',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='PlayerAugmentation_MOD_SPLIT_RANKINGS', serialize=False, to='stats.Player')),
                ('fighter_attacker_counter', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-3), django.core.validators.MaxValueValidator(3)])),
            ],
            options={
                'db_table': 'Player_MOD_SPLIT_RANKINGS',
            },
        ),
    ]
