# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-17 09:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stats', '0034_mod_rating_by_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftBucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_type', models.CharField(choices=[('NO_FILTER', 'no filter'), ('NO_BOMBS_JUICE', 'no bombs nor juice'), ('BOMBS', 'bomb sorties only with no juice'), ('JUICE', 'juiced (upgraded engine/fuel)'), ('ALL', 'all')], default='NO_FILTER', max_length=16)),
                ('total_flight_time', models.BigIntegerField(db_index=True, default=0)),
                ('khr', models.FloatField(db_index=True, default=0)),
                ('gkhr', models.FloatField(db_index=True, default=0)),
                ('kd', models.FloatField(db_index=True, default=0)),
                ('gkd', models.FloatField(db_index=True, default=0)),
                ('accuracy', models.FloatField(db_index=True, default=0)),
                ('bomb_rocket_accuracy', models.FloatField(db_index=True, default=0)),
                ('plane_survivability', models.FloatField(db_index=True, default=0)),
                ('pilot_survivability', models.FloatField(db_index=True, default=0)),
                ('plane_lethality', models.FloatField(db_index=True, default=0)),
                ('pilot_lethality', models.FloatField(db_index=True, default=0)),
                ('elo', models.IntegerField(db_index=True, default=1500)),
                ('rating', models.IntegerField(db_index=True, default=0)),
                ('total_sorties', models.BigIntegerField(default=0)),
                ('score', models.BigIntegerField(default=0)),
                ('ahr', models.FloatField(default=0)),
                ('ahd', models.FloatField(default=0)),
                ('kills', models.BigIntegerField(default=0)),
                ('ground_kills', models.BigIntegerField(default=0)),
                ('assists', models.BigIntegerField(default=0)),
                ('killboard_planes', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('killboard_ground', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('coalition', models.IntegerField(choices=[(0, 'neutral'), (1, 'Allies'), (2, 'Axis')], default=0)),
                ('aircraft_lost', models.BigIntegerField(default=0)),
                ('deaths', models.BigIntegerField(default=0)),
                ('captures', models.BigIntegerField(default=0)),
                ('bailouts', models.BigIntegerField(default=0)),
                ('ditches', models.BigIntegerField(default=0)),
                ('landings', models.BigIntegerField(default=0)),
                ('in_flight', models.BigIntegerField(default=0)),
                ('crashes', models.BigIntegerField(default=0)),
                ('shotdown', models.BigIntegerField(default=0)),
                ('ammo_shot', models.BigIntegerField(default=0)),
                ('ammo_hit', models.BigIntegerField(default=0)),
                ('bomb_rocket_shot', models.BigIntegerField(default=0)),
                ('bomb_rocket_hit', models.BigIntegerField(default=0)),
                ('sorties_plane_was_hit', models.BigIntegerField(default=0)),
                ('plane_survivability_counter', models.BigIntegerField(default=0)),
                ('pilot_survivability_counter', models.BigIntegerField(default=0)),
                ('plane_lethality_counter', models.BigIntegerField(default=0)),
                ('pilot_lethality_counter', models.BigIntegerField(default=0)),
                ('distinct_enemies_hit', models.BigIntegerField(default=0)),
                ('pilot_kills', models.BigIntegerField(default=0)),
                ('has_juiced_variant', models.BooleanField(db_index=True, default=False)),
                ('has_bomb_variant', models.BooleanField(db_index=True, default=False)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='stats.Object')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='stats.Tour')),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'AircraftBucket_MOD_STATS_BY_AIRCRAFT',
            },
        ),
        migrations.CreateModel(
            name='AircraftKillboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_1_kills', models.BigIntegerField(default=0)),
                ('aircraft_1_shotdown', models.BigIntegerField(default=0)),
                ('aircraft_1_assists', models.BigIntegerField(default=0)),
                ('aircraft_1_pk_assists', models.BigIntegerField(default=0)),
                ('aircraft_2_kills', models.BigIntegerField(default=0)),
                ('aircraft_2_shotdown', models.BigIntegerField(default=0)),
                ('aircraft_2_assists', models.BigIntegerField(default=0)),
                ('aircraft_2_pk_assists', models.BigIntegerField(default=0)),
                ('aircraft_1_distinct_hits', models.BigIntegerField(default=0)),
                ('aircraft_2_distinct_hits', models.BigIntegerField(default=0)),
                ('aircraft_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mod_stats_by_aircraft.AircraftBucket')),
                ('aircraft_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mod_stats_by_aircraft.AircraftBucket')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='stats.Tour')),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'AircraftKillboard_MOD_STATS_BY_AIRCRAFT',
            },
        ),
        migrations.CreateModel(
            name='SortieAugmentation',
            fields=[
                ('sortie', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='SortieAugmentation_MOD_STATS_BY_AIRCRAFT', serialize=False, to='stats.Sortie')),
                ('sortie_stats_processed', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'db_table': 'Sortie_MOD_STATS_BY_AIRCRAFT',
            },
        ),
    ]
