# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-04 08:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import mod_stats_by_aircraft.aircraft_mod_models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0034_mod_rating_by_type'),
        ('mod_stats_by_aircraft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraftbucket',
            name='aircraft_lost_to_aa',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aircraftbucket',
            name='aircraft_lost_to_accident',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aircraftbucket',
            name='ammo_breakdown',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=mod_stats_by_aircraft.aircraft_mod_models.default_ammo_breakdown),
        ),
        migrations.AddField(
            model_name='aircraftbucket',
            name='deaths_to_aa',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aircraftbucket',
            name='deaths_to_accident',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aircraftbucket',
            name='plane_lethality_no_assists',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='aircraftbucket',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='stats.Player'),
        ),
        migrations.AddField(
            model_name='sortieaugmentation',
            name='player_stats_processed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
