# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-28 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_stats_by_aircraft', '0002_pilot_aircraft_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraftbucket',
            name='reset_accident_aa_stats',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='sortieaugmentation',
            name='fixed_aa_accident_stats',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
