# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-05 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_stats_by_aircraft', '0003_fix_aa_accident_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraftbucket',
            name='reset_elo',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='aircraftkillboard',
            name='reset_kills_turret_bug',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='sortieaugmentation',
            name='fixed_doubled_turret_killboards',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
