# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-06 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_stats_by_aircraft', '0004_fix_killboard_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraftkillboard',
            name='reset_player_loses',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='sortieaugmentation',
            name='added_player_kb_losses',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
