# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-13 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_stats_by_aircraft', '0008_recompute_defensive_ammo_breakdowns'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortieaugmentation',
            name='fixed_captures',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
