# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-25 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_stats_by_aircraft', '0009_fix_captures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraftbucket',
            name='rating',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
    ]
